### ISSUE TITLE
Not supporting ה'תשסע

### ISSUE THREAD

**Issue by talbenbasat** [OriHoch/python-hebrew-numbers#3]
Hi,

nice but few things:
1. you don't support the ה' in the beginning
2. we map instead of dict?

Tal

**Comment by OriHoch** [comment]
hi @talbenbasat, forgot about this repo for a while..

I think number 2 was fixed by @ninjaaron just now

regarding 1, I didn't understand the bug.. I'm also not too familiar with Gematryia rules

feel free to send a pull request with any suggested changes

**Comment by ninjaaron** [comment]
@talbenbasat I added the functionality you asked for *for date formats*, so if you put ה'תשע"ז in, you get 5777 (the current Hebrew year). It multiplies everything before the single quote (or geresh) by 1000. Because Hebrew numbers in the single digits are frequently indicated by a following geresh, I opted to ignore a trailing geresh, but this is incorrect for some formats, which may use a final geresh to indicate thousands. I opted to follow the rules for dates, since this is probably the most common place where thousands occur.

@OriHoch The thousand's place in gematria is sometimes indicated by a geresh, which acts as a multiplier of a thousand for the preceding number. While Hebrew years are normally written only to the hundred's place (תשע"ז = 777), the full year, is written ה'תשע"ז, as indicated above.

We might try having different modes for different ways of dealing with the geresh if anyone wants that, but frankly, outside of dates thousands are used so infrequently in gematria that I'm not going to work on it unless someone needs it. (It is probably used in Kabbalah sometimes, but I don't know much about that).
