### ISSUE TITLE
should provide an int_to_gematria function

### ISSUE THREAD

**Issue by OriHoch** [OriHoch/python-hebrew-numbers#6]
```bash
>>> from hebrew_numbers import int_to_gematria
>>> int_to_gematria(298)
רח"צ
```

### implementation notes
* should use [hebrew-special-numbers](https://github.com/chaimleib/hebrew-special-numbers) to implement it

**Comment by ninjaaron** [comment]
I don't know how soon I will get to this, but I need this functionality for a project I'm doing at work. It will get done eventually.

**Comment by ninjaaron** [comment]
Alright, I'm ready to start working on this. I thought we maybe should talk about how we want to distribute hebrew-special-numbers. I opened an issue there to see if @chaimleib has any thoughts about it.  https://github.com/chaimleib/hebrew-special-numbers/issues/3

My preference is to make it a git submodule so it will be easier to pull from upstream as part of the regular workflow, but I didn't want to make a major decision like that without running it by you. Some people really don't like submodules!

**Comment by OriHoch** [comment]
hebrew-special-numbers is a python package, so you can install it using pip

if they don't publish to pypi, you can do this:

pip install --upgrade https://github.com/chaimleib/hebrew-special-numbers/archive/master.zip

**Comment by OriHoch** [comment]
also, bear in mind that python-hebrew-numbers is also a python package, installable by pip, so git submodule is not a good solution for that use-case - as most users will install using pip

**Comment by ninjaaron** [comment]
Well, the fact that python-hebrew-numbers (PHN) is a python package wouldn't keep us from using a submodule. It would be the same as if we just copied hebrew-special-numbers (HSN) directly into the PHN source tree. We'd have to include it with package-resources or (preferably) MANIFEST.in, but then it will be included when you update the pypi repo.

HSN isn't in pypi at the moment. If it gets in, just pulling from there is definitely the way to go. I'm just thinking about the installation path for potential users at this point. They should be able to install from pip and have everything be there.

I'm definitely not an expert in setuptools, so if there is a way to pull HSN from github using PHN's setup.py, that's totally fine with me also -- I just have no idea how to do it! (and I do know how to do it with a submodule and MANIFEST.in)

**Comment by OriHoch** [comment]
I see what you mean..

I'm fine with the submodule solution but I think the best solution will be to make hebrew-special-numbers into a pypi package.. you don't need the package maintainer to do it, you can do it yourself

but, if for some reason you prefer submodule, you are welcome to do it that way

**Comment by ninjaaron** [comment]
Also note that the purpose of HSN setup.py file is primarily to set up the test environment. It's not a python project perse, more a pile of (very useful) serialized data and docs. The setup.py pulls along the yaml files using `data_files`. We could work with that, but it would involve importing the HSN test module, extracting its path, and then finding the yaml relative to that.

All that is totally possible and not really very difficult, but the way HSN is designed (platform independence as a stated goal) made my head go to vendoring first.

I'd be happy to upload HSN to pypi, if you prefer that route. I just don't want to step on @chaimleib's feet in case he has some plans of his own. I could also submit a PR to HSN so the data can be imported from his package in a more normal way with python, but I'd like to get his thoughts about how he envisions his project being distributed.

I definitely didn't want to commit the PHN to submodules without having this discussion first because they add an extra layer of fiddling and are kind of putzy to back out of if you change your mind. I also agree that pulling from pypi would be ideal. That's just also something to consider carefully, since, if HSN moves away from python for testing, we'll have to fork or vendor it anyway.

I will still work on our end of the code in the meantime, but I probably will hold off on pushing anything until we get Chaim-Leib's opinion at the very least.

**Comment by OriHoch** [comment]
don't worry about it, go with the submodule solution

**Comment by chaimleib** [comment]
I looked over the docs for setup.py, and I couldn't see a way to pull in anything but another python package as a dependency. It might be possible to hack some net and fs commands into setup.py, but that sounds very fragile.

If I were to make hsn into a Python package, I think I would create a separate repo and submodule this hsn, since that would let me set the location of the data files and allow me to develop and debug most simply. However, I'm not planning on doing that soon.

I think the quickest solution for now is to use git submodule inside phn.

**Comment by ninjaaron** [comment]
Alright. Will do. I have the code working on my system (just copy-pasta'd the example, really). I'll push the code and add hebrew-special-numbers as submodule tomorrow. Thanks again, @chaimleib. This will be really helpful for my project.

@OriHoch I don't know how adding a submodule will affect the continuous integration thing, but I suspect intervention will be necessary.

**Comment by ninjaaron** [comment]
So, the code is up in the dev branch, but as expected, this totally broke Travis. It passes on my system with 3.6 and 2.7.

I'll start looking more at this Travis stuff.

**Comment by OriHoch** [comment]
:+1: if you want my help - open a pull request and prefix the title with [WIP] = work in progress so we know not to merge it
that way I will be able to see and comment on your changes

**Comment by ninjaaron** [comment]
Is there a way to run the tests on the Travis server thing without committing to github? I don't want to junk up the history with a bunch of broken commits from me learning Travis!

**Comment by chaimleib** [comment]
You can do development on a separate git branch and have Travis test that. When ready to merge into master, you can squash your commits into one commit to keep the master branch history looking clean.

**Comment by OriHoch** [comment]
@ninjaaron we run travis automatically on pull requests, if you open a pull request, every commit you push will be tested
I suggest not to use dev branch - but instead work on your own fork, and use feature branches
don't worry about junk commits - when pull request is merged, I'll squash it

**Comment by OriHoch** [comment]
see https://guides.github.com/activities/forking/
